---
- name: transfer nginx source
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name=nginx state=latest

- name: transfer nginx conf
  template: src=nginx.j2 dest=/etc/nginx/conf.d/default.conf
  notify:
    - restart nginx

- name: start nginx
  service: name=nginx state=started enabled=true
