---
- hosts: webservers
  remote: root
  vars: 
    
  tasks:
    - name: set yum source
      template: src="$HOME/nginx.repo" dest="/etc/yum.repos.d/nginx.repo" owner="root" group="root" mode="0644"
    
    - name: install nginx
      yum: name="nginx" state="latest"
    
    - name: set nginx  
